import { Project } from "./types";

export const projects: Project[] = [
    {
        id: "portfolio",
        title: "Portfolio Website",
        subtitle: "Personal Developer Portfolio",
        description: "Modern, animated portfolio showcasing skills, projects & experience with stunning UI/UX, glassmorphism, and smooth animations.",
        tech: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
        link: "https://rajprem.vercel.app/",
        type: "portfolio",
        featured: true,
        stats: [
            { label: "Performance", value: "98%" },
            { label: "Accessibility", value: "100%" },
        ],
        color: "from-cyan-500 via-blue-500 to-purple-500",
        accentColor: "cyan",
    },
    {
        id: "vriddhi",
        title: "Vriddhi Platform",
        subtitle: "Platform Management System",
        description: "Comprehensive platform management solution with dashboard analytics, user management, and real-time data visualization.",
        tech: ["React", "Node.js", "MongoDB", "Express"],
        link: "https://vriddhi-app.vercel.app/",
        type: "webapp",
        featured: true,
        stats: [
            { label: "Users", value: "500+" },
            { label: "Features", value: "25+" },
        ],
        color: "from-emerald-500 via-teal-500 to-cyan-500",
        accentColor: "emerald",
    },
    {
        id: "student-app",
        title: "Student Management",
        subtitle: "Educational Platform UI",
        description: "Beautiful frontend interface for managing student data, attendance tracking, and academic performance visualization.",
        tech: ["React", "CSS3", "JavaScript", "Responsive Design"],
        link: "https://student-app-green.vercel.app/",
        type: "frontend",
        stats: [
            { label: "Components", value: "40+" },
            { label: "Screens", value: "12" },
        ],
        color: "from-green-500 via-lime-500 to-yellow-500",
        accentColor: "green",
    },
    {
        id: "react-icons",
        title: "React Icons Contribution",
        subtitle: "Open Source Contribution",
        description: "Contributed a custom Bow icon to the popular react-icons library. Successfully merged PR adding new icon to Font Awesome set.",
        tech: ["React", "SVG", "Open Source", "TypeScript"],
        link: "https://github.com/react-icons/react-icons/pull/1095",
        github: "https://github.com/PREM015/react-icons/tree/add-fa-bow-icon",
        type: "opensource",
        featured: true,
        stats: [
            { label: "Downloads", value: "1M+/week" },
            { label: "Stars", value: "11k+" },
        ],
        color: "from-pink-500 via-rose-500 to-red-500",
        accentColor: "pink",
    },
    {
        id: "vscode-extension",
        title: "Faah On Fail",
        subtitle: "VS Code Extension",
        description: "Fun VS Code extension that plays 'Faah' sound on build failures. Makes debugging more entertaining with audio feedback.",
        tech: ["TypeScript", "VS Code API", "Node.js"],
        link: "https://marketplace.visualstudio.com/items?itemName=premdev.faah-on-fail",
        type: "extension",
        stats: [
            { label: "Installs", value: "100+" },
            { label: "Rating", value: "⭐⭐⭐⭐⭐" },
        ],
        color: "from-blue-600 via-indigo-500 to-purple-600",
        accentColor: "indigo",
    },
    {
        id: "npm-package",
        title: "create-nextjs-backend",
        subtitle: "NPM CLI Package",
        description: "CLI tool to instantly scaffold Next.js backend with pre-configured API routes, database setup, and authentication boilerplate.",
        tech: ["Node.js", "CLI", "NPM", "JavaScript"],
        link: "https://www.npmjs.com/package/create-nextjs-backend",
        type: "npm",
        stats: [
            { label: "Downloads", value: "200+" },
            { label: "Version", value: "1.0.0" },
        ],
        color: "from-red-500 via-orange-500 to-yellow-500",
        accentColor: "orange",
    },
    {
        id: "solar-system",
        title: "3D Solar System",
        subtitle: "Three.js Visualization",
        description: "Interactive 3D solar system with realistic planet orbits, textures, and animations built with Three.js, HTML & CSS.",
        tech: ["Three.js", "HTML5", "CSS3", "WebGL"],
        link: "https://github.com/PREM015/threejs-project",
        github: "https://github.com/PREM015/threejs-project",
        type: "threejs",
        stats: [
            { label: "Planets", value: "8" },
            { label: "3D Objects", value: "50+" },
        ],
        color: "from-purple-600 via-violet-500 to-indigo-600",
        accentColor: "violet",
    },
    {
        id: "selection-sort",
        title: "Selection Sort Visualizer",
        subtitle: "Algorithm Visualization",
        description: "Interactive visualization of selection sort algorithm with step-by-step animation, speed control, and array size customization.",
        tech: ["JavaScript", "HTML5", "CSS3", "Algorithms"],
        link: "https://github.com/PREM015/selection-sort-",
        github: "https://github.com/PREM015/selection-sort-",
        type: "algorithm",
        stats: [
            { label: "Complexity", value: "O(n²)" },
            { label: "Animations", value: "Smooth" },
        ],
        color: "from-amber-500 via-orange-500 to-red-500",
        accentColor: "amber",
    },
];
